# Generated by Django 4.1.7 on 2023-04-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='places',
        ),
    ]
